set tabstop=2
set shiftwidth=2
set expandtab

set number
set autoindent

" Enable modern Vim features not compatible with Vi spec.
set nocompatible

" Include the various VIM configs for different environments.
{% if config_file_includes is mapping and 'vimrc' in config_file_includes %}{% for include in config_file_includes['vimrc']|sort %}
{{ include }}{% endfor %}{% else %}
" No other configs to include{% endif %}

filetype plugin indent on
syntax on
